name: Apex Options Daily Scanner

on:
  schedule:
    # Runs at 04:30 UTC (10:00 AM IST) and 09:30 UTC (3:00 PM IST)
    # Cron format is in UTC. IST is UTC + 5:30.
    - cron: '30 4 * * 1-5'
    - cron: '30 9 * * 1-5'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy scipy pytz

      - name: Run Apex Scanner
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python worker1.py  # Replace with your actual filename
